"""initial schema: sessions, turns, evaluations

Revision ID: 6741599e8157
Revises:
Create Date: 2026-09-18 10:12:33.067748

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6741599e8157"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("sanitized_name", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("retrieval_backend", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(op.f("ix_sessions_candidate_id"), "sessions", ["candidate_id"], unique=False)
    op.create_index(op.f("ix_sessions_role"), "sessions", ["role"], unique=False)
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=False)
    op.create_table(
        "evaluations",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("target_role", sa.String(length=64), nullable=False),
        sa.Column("rubric_fit_index", sa.Float(), nullable=False),
        sa.Column("routing_confidence", sa.Float(), nullable=False),
        sa.Column("recommendation", sa.String(length=32), nullable=False),
        sa.Column("turns_completed", sa.Integer(), nullable=False),
        sa.Column("latency_compliance", sa.Float(), nullable=False),
        sa.Column("competency_scores", sa.JSON(), nullable=False),
        sa.Column("eliminations", sa.JSON(), nullable=False),
        sa.Column("flagged_limitations", sa.JSON(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_evaluations_recommendation"), "evaluations", ["recommendation"], unique=False
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("speaker", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("offset_ms", sa.Float(), nullable=False),
        sa.Column("turnaround_ms", sa.Float(), nullable=True),
        sa.Column("within_budget", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_turns_session_id"), "turns", ["session_id"], unique=False)
    op.create_index("ix_turns_session_offset", "turns", ["session_id", "offset_ms"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_turns_session_offset", table_name="turns")
    op.drop_index(op.f("ix_turns_session_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_index(op.f("ix_evaluations_recommendation"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_role"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_candidate_id"), table_name="sessions")
    op.drop_table("sessions")
    # ### end Alembic commands ###
